version: '3.4'

services:
  elkexampleapi.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=63467
    ports:
      - "63467:80"
    volumes:
      - ${APPDATA}/ASP.NET/Http:/root/.aspnet/http:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro